name: bannet_movil_t
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.63.0
  flutter_pdfview: 1.4.0
  syncfusion_flutter_pdfviewer: ^28.1.38
  provider: ^6.1.2
  path_provider: ^2.0.14
  percent_indicator: ^4.2.4
  flutter_local_notifications: ^18.0.1
  open_file: ^3.5.10
  pdf: ^3.11.1
  shared_preferences: ^2.1.1
  printing: ^5.11.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  font_awesome_flutter: ^10.5.0
  permission_handler: ^11.3.1


flutter:
  uses-material-design: true
  assets:
  - assets/images/Versión-Móvil_FONDO_Yape.png
  - assets/images/Versión-Móvil_FONDO_BCP.png
  - assets/images/Versión-Móvil_FONDO_BBVA.png
  - assets/images/
  - assets/pdfs/
  - assets/logo/
  fonts:
  - family: MyCustomFont
    fonts:
    - asset: assets/fonts/FontsFree-Net-TurismoCF-100.ttf
      weight: 100
