name: bannet_movil_t
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.63.0
  flutter_pdfview: 1.4.0
  syncfusion_flutter_pdfviewer: ^28.1.38
  path_provider: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  font_awesome_flutter: ^10.5.0
  permission_handler: ^10.0.0


flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/pdfs/
  - assets/logo/
  fonts:
  - family: MyCustomFont
    fonts:
    - asset: assets/fonts/FontsFree-Net-TurismoCF-100.ttf
      weight: 100
